[package]
name = "day-3"
description = "https://adventofcode.com/2024/day/3"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part_1"

[[bin]]
name = "part_2"

[dependencies]
regex.workspace = true

[dev-dependencies]
rstest.workspace = true
